### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Robindeko** [barisdemirdelen/homeassistant-greenchoice#23]
Ik krijg versie 1.5.1 niet werkend op mijn installatie.
HA versie is 2025.3.4

Hier een stuk log van de errors die hij geeft:

2025-03-28 11:58:01.299 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up greenchoice platform for sensor: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 107, in setup_platform
    throttled_api_update(greenchoice_api)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 184, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 124, in throttled_api_update
    api_result = api.update()
  File "/config/custom_components/greenchoice/api.py", line 208, in update
    self.update_contract_values(self.result)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/api.py", line 248, in update_contract_values
    pricing_details = self.get_rates()
  File "/config/custom_components/greenchoice/api.py", line 191, in get_rates
    return Rates.from_dict(pricing_details)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/model.py", line 233, in from_dict
    beginDatum=datetime.fromisoformat(data.get("beginDatum")),
                                      ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'


heeft iemand enig idee wat hier mis gaat?

Alvast bedankt!

**Comment by Robindeko** [comment]
Hi, Thanks for responding. yes that page works, It shows me my current prices.
And yes, it always fails.

Is there any extra logging I can turn on or something to debug the issue?

**Comment by barisdemirdelen** [comment]
I am working on changing that specific api call on the side, it seems Greenchoice is using yet again another api for this. You can already try if it works with the pre-release v2.3.0-alpha version. If it doesnt work, it should also give a better error message.

**Comment by Robindeko** [comment]
Thanks for the update. I've installed the 2.3.0 alpha version and the error is gone!

Unfortunately, I don't receive any data, but I thank this is caused by Greenchoice themselves.
When I login to "Mijn Greenchoice" I only see historical data up to 2023, I don't see actual data.
I've contacted them to resolve this issue.

**Comment by Robindeko** [comment]
Maybe I found the cause for the problems.
I used Greenchoice for several years.
In 2023 I switched to another provider and in 2024 I switched back to Greenchoice again.
When I now login to "Mijn Greenchoice"  I have to "addresses" in the top bar with 2 seperate Customer Numbers.

Is there any way to set the Customer number for the API retrieval?

**Comment by Robindeko** [comment]
I manually set my customer number in "api.py" on line 112 and now I see my values!

**Comment by barisdemirdelen** [comment]
Currently it only queries the preferred contract, so whatever is selected on the website for viewing. I have intentions to add a feature to specify contract id instead. It would also be helpful for people with multiple contracts.
